#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      keyid: ${docker_gpg_key_id}

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - ca-certificates
  - gnupg
  - docker-ce
  - docker-ce-cli

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - curl -o /usr/bin/p-env https://raw.githubusercontent.com/humpangle/dotfiles/master/scripts/p-env
  - chmod 755 /usr/bin/p-env
  - docker login --username ${container_registry_user_name} --password ${container_registry_password}
  - docker pull ${container_image_name}
