- name: Some
  hosts: staging
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present

    - name: Run Docker container  # noqa xx
      ansible.builtin.command:
        argv:
          - docker
          - run
          - -d
          - --name
          - "{{ CONTAINER_NAME }}"
          - -p
          - 80:80
          - "{{ CONTAINER_IMAGE_NAME }}"
          - --env-file="{{ ENV_FILENAME }}"
      register: my_output
      changed_when: my_output.rc != 0
